config/routes.rb
# encoding: utf-8
#
# Redmine plugin to add pagination links to my page queries
#
# Copyright © 2018 Stephan Wenzel <stephan.wenzel@drwpatent.de>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

RedmineApp::Application.routes.draw do
  
  resource :my_page_paginations, :only => [] do
    collection do
      get "update/:id", :to => "my_page_paginations#update", :as => "update", :id => /.+/
    end
  end
  
end #do

app/controllers/my_page_paginations_controller.rb
# encoding: utf-8
#
# Redmine plugin to add pagination links to my page queries
#
# Copyright © 2018 Stephan Wenzel <stephan.wenzel@drwpatent.de>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

class MyPagePaginationsController < ApplicationController

  before_action :authorize_loggedin

  def update
    my_page_pagination = User.current.pref.my_page_pagination.presence || {}
    per_page = params[:per_page]
        page = params[:page]
    page= "1" if per_page.present? #reset page to avoid pages off range after altering per_page
    User.current.pref.my_page_pagination = my_page_pagination.deep_merge(params[:id] => {"per_page" => per_page, "page" => page}.compact)
    User.current.pref.save
    redirect_to :back
  end #def
  
  private

  def authorize_loggedin
    deny_access unless User.current.logged?
  end #def
  
end #class

app/views/my/patched_blocks/_issues.erb
<div class="contextual">
  <%= link_to_function l(:label_options), "$('##{block}-settings').toggle();", :class => 'icon-only icon-settings', :title => l(:label_options) %>
</div>

<h3>
  <%= "#{query.project} |" if query.project %>
  <%= link_to query.name, _project_issues_path(query.project, query.as_params) %>
  (<%= query.issue_count %>)
</h3>

<div id="<%= block %>-settings" style="display:none;">
  <%= form_tag(my_page_path, :remote => true) do %>
    <div class="box">
      <%= render_query_columns_selection(query, :name => "settings[#{block}][columns]") %>
    </div>
    <p>
      <%= submit_tag l(:button_save) %>
      <%= link_to_function l(:button_cancel), "$('##{block}-settings').toggle();" %>
    </p>
  <% end %>
</div>

<% if issues.any? %>
  <%= render :partial => 'issues/list',
             :locals => {
               :issues => issues,
               :query => query,
               :query_options => {
                 :sort_param => "settings[#{block}][sort]",
                 :sort_link_options => {:method => :post, :remote => true}
               }
             } %>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>
<%- if query.id.present? || query.name.present? %>
  <span class="pagination"><%= pagination_links_full( 
        @issue_pages, 
        query.issue_count, 
        :per_page_links => true 
      ) { |text, parameters, options| link_to text, update_my_page_paginations_path(query.id.present? ? "#{query.id}" : Digest::MD5.hexdigest(query.name), parameters ), options } %></span>
  <%- end %>
<% content_for :header_tags do %>
<%= auto_discovery_link_tag(:atom,
                            _project_issues_path(query.project, query.as_params.merge(:format => 'atom', :key => User.current.rss_key)),
                            {:title => query.name}) %>
<% end %>